config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :registered_applications
  get 'welcome/index'

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#index', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application

  validates :name, presence: true
  validates :registered_application, presence: { message: "can\'t be blank" }
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  scope :visible_to, -> (user) { where(user_id: user.id) }

  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
  validates :url, uniqueness: true

  def count_events
    events = self.events.group_by(&:name)
    each_event = Hash.new(0)
    events.each do |key, _value|
      each_event[key] = events[key].count
    end
    each_event
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  skip_before_action :verify_authenticity_token
  before_action :set_access_control_headers

  def create
    event = Event.create(event_params)
    event.registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if event.save
      render json: event, status: :created
    else
      render json: { errors: event.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.permit(:name)
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_in_path_for(*)
    registered_applications_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.visible_to(current_user)
    authorize @registered_applications
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    @events = @registered_application.count_events
    authorize @registered_application
  end

  def new
    @registered_application = RegisteredApplication.new
    authorize @registered_application
  end

  def create
    registered_application = current_user.registered_applications.build(app_params)
    authorize registered_application
    if registered_application.save
      flash[:notice] = 'Your application was registered'
      redirect_to registered_applications_path
    else
      flash[:error] = 'Your application was not registered'
      redirect_to registered_applications_path
    end
  end

  def destroy
    registered_application = RegisteredApplication.find(params[:id])
    authorize registered_application
    if registered_application.destroy
      flash[:notice] = 'Your application is no longer registered.'
      redirect_to registered_applications_path
    else
      flash[:error] = 'Your application is still registered'
      render :show
    end
  end

  private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocmetrics
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Blocmetrics", root_path
        %li= link_to "About", about_path
        - if current_user && !current_page?(controller: 'registered_applications', action: 'index')
          %li= link_to 'My applications', registered_applications_path
        .pull-right.user-info
          - if current_user
            Hello
            = current_user.email
            \!
            = link_to "Sign out", destroy_user_session_path, method: :delete
          - else
            = link_to "Sign In", new_user_session_path
            or
            = link_to "Sign Up", new_user_registration_path
      -if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"}
          = flash[:notice]
      -elsif flash[:error]
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"}
          = flash[:error]
      -elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"}
          = flash[:alert]
      = yield

app/views/registered_applications/_form.html.haml
= form_for registered_application do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'Enter name'
  .form-group
    = f.label :url
    = f.text_field :url, class: 'form-control', placeholder: 'Enter URL'
  .form-group
    = f.submit 'Save', class: 'btn btn-success'

app/views/registered_applications/index.html.haml
%h1 Registered Applications
- if policy(RegisteredApplication.new).create?
  = link_to 'Register Application', new_registered_application_path, class: 'btn btn-success'
- @registered_applications.each do |app|
  .media
    .media-body
      .media-heading
        %p= link_to app.name, app

app/views/registered_applications/new.html.haml
.row
  .col-md-4
    %p Register your application
    %ul
      %li Provide the name of your application
      %li Provide its URL
  .col-md-8
    = render partial: 'registered_applications/form', locals: { registered_application: @registered_application }

app/views/registered_applications/show.html.haml
%h1= @registered_application.name
%p= link_to @registered_application.url
%h3 Events
- @events.each do |key, value|
  .media
    .media-body
      .media-heading
        %tr
          %td= key
          %td= value
- if policy(@registered_application).destroy?
  = link_to 'Unregister', @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to unregister your app?' }

app/views/welcome/about.html.haml
%h1 Welcome#about
%p Find me in app/views/welcome/about.html.haml

app/views/welcome/index.html.haml
%br/
.jumbotron
  %h1 Blocmetrics
  %p Blocmetrics is an analytics service analytics service which:

  %p 1. enables users to track events on their website

  %p 2. captures those events to a database via a server-side API

  %p 3. displays the event data